const countriesData1 = [];
    fetch("https://restcountries.com/v3.1/all")
        .then((response) => response.json())
        .then((data) => {
            for (let i = 0; i < data.length; i++) {
                if (data[i].capital === undefined || !data[i].capital) {
                    data[i].capital = ["None capital"];
                }
                if (!data[i].languages || data[i].languages === undefined) {
                    data[i].languages = "";
                }
                let langs = Object.values(data[i].languages);
                countriesData1.push({
                    name: data[i].name.common,
                    capital: data[i].capital[0].toString(),
                    population: data[i].population,
                    flag: data[i].flags.png,
                    languages: langs.toString().replace(/,/g, ", "),
                });
            }
            // console.log(countriesData1);
            // return countriesData1;
        })
        .catch((error) => console.error(error));

const countriesData = [
    {
        name: "Iceland",
        capital: "Reykjavik",
        population: 366425,
        flag: "https://flagcdn.com/w320/is.png",
        languages: "Icelandic",
    },
    {
        name: "Japan",
        capital: "Tokyo",
        population: 125836021,
        flag: "https://flagcdn.com/w320/jp.png",
        languages: "Japanese",
    },
    {
        name: "New Caledonia",
        capital: "Nouméa",
        population: 271960,
        flag: "https://flagcdn.com/w320/nc.png",
        languages: "French",
    },
    {
        name: "Somalia",
        capital: "Mogadishu",
        population: 15893219,
        flag: "https://flagcdn.com/w320/so.png",
        languages: "Arabic, Somali",
    },
    {
        name: "Jordan",
        capital: "Amman",
        population: 10203140,
        flag: "https://flagcdn.com/w320/jo.png",
        languages: "Arabic",
    },
    {
        name: "Caribbean Netherlands",
        capital: "Kralendijk",
        population: 25987,
        flag: "https://flagcdn.com/w320/bq.png",
        languages: "English, Dutch, Papiamento",
    },
    {
        name: "Algeria",
        capital: "Algiers",
        population: 44700000,
        flag: "https://flagcdn.com/w320/dz.png",
        languages: "Arabic",
    },
    {
        name: "New Zealand",
        capital: "Wellington",
        population: 5084300,
        flag: "https://flagcdn.com/w320/nz.png",
        languages: "English, Māori, New Zealand Sign Language",
    },
    {
        name: "Chile",
        capital: "Santiago",
        population: 19116209,
        flag: "https://flagcdn.com/w320/cl.png",
        languages: "Spanish",
    },
    {
        name: "France",
        capital: "Paris",
        population: 67391582,
        flag: "https://flagcdn.com/w320/fr.png",
        languages: "French",
    },
    {
        name: "Lesotho",
        capital: "Maseru",
        population: 2142252,
        flag: "https://flagcdn.com/w320/ls.png",
        languages: "English, Sotho",
    },
    {
        name: "Lebanon",
        capital: "Beirut",
        population: 6825442,
        flag: "https://flagcdn.com/w320/lb.png",
        languages: "Arabic, French",
    },
    {
        name: "Turks and Caicos Islands",
        capital: "Cockburn Town",
        population: 38718,
        flag: "https://flagcdn.com/w320/tc.png",
        languages: "English",
    },
    {
        name: "Norway",
        capital: "Oslo",
        population: 5379475,
        flag: "https://flagcdn.com/w320/no.png",
        languages: "Norwegian Nynorsk, Norwegian Bokmål, Sami",
    },
    {
        name: "Peru",
        capital: "Lima",
        population: 32971846,
        flag: "https://flagcdn.com/w320/pe.png",
        languages: "Aymara, Quechua, Spanish",
    },
    {
        name: "Syria",
        capital: "Damascus",
        population: 17500657,
        flag: "https://flagcdn.com/w320/sy.png",
        languages: "Arabic",
    },
    {
        name: "Nauru",
        capital: "Yaren",
        population: 10834,
        flag: "https://flagcdn.com/w320/nr.png",
        languages: "English, Nauru",
    },
    {
        name: "Fiji",
        capital: "Suva",
        population: 896444,
        flag: "https://flagcdn.com/w320/fj.png",
        languages: "English, Fijian, Fiji Hindi",
    },
    {
        name: "Honduras",
        capital: "Tegucigalpa",
        population: 9904608,
        flag: "https://flagcdn.com/w320/hn.png",
        languages: "Spanish",
    },
    {
        name: "Benin",
        capital: "Porto-Novo",
        population: 12123198,
        flag: "https://flagcdn.com/w320/bj.png",
        languages: "French",
    },
    {
        name: "Palau",
        capital: "Ngerulmud",
        population: 18092,
        flag: "https://flagcdn.com/w320/pw.png",
        languages: "English, Palauan",
    },
    {
        name: "Saint Martin",
        capital: "Marigot",
        population: 38659,
        flag: "https://flagcdn.com/w320/mf.png",
        languages: "French",
    },
    {
        name: "Svalbard and Jan Mayen",
        capital: "Longyearbyen",
        population: 2562,
        flag: "https://flagcdn.com/w320/sj.png",
        languages: "Norwegian",
    },
    {
        name: "Montenegro",
        capital: "Podgorica",
        population: 621718,
        flag: "https://flagcdn.com/w320/me.png",
        languages: "Montenegrin",
    },
    {
        name: "Estonia",
        capital: "Tallinn",
        population: 1331057,
        flag: "https://flagcdn.com/w320/ee.png",
        languages: "Estonian",
    },
    {
        name: "Grenada",
        capital: "St. George's",
        population: 112519,
        flag: "https://flagcdn.com/w320/gd.png",
        languages: "English",
    },
    {
        name: "Singapore",
        capital: "Singapore",
        population: 5685807,
        flag: "https://flagcdn.com/w320/sg.png",
        languages: "Chinese, English, Malay, Tamil",
    },
    {
        name: "Mali",
        capital: "Bamako",
        population: 20250834,
        flag: "https://flagcdn.com/w320/ml.png",
        languages: "French",
    },
    {
        name: "Kazakhstan",
        capital: "Nur-Sultan",
        population: 18754440,
        flag: "https://flagcdn.com/w320/kz.png",
        languages: "Kazakh, Russian",
    },
    {
        name: "Spain",
        capital: "Madrid",
        population: 47351567,
        flag: "https://flagcdn.com/w320/es.png",
        languages: "Spanish",
    },
    {
        name: "Monaco",
        capital: "Monaco",
        population: 39244,
        flag: "https://flagcdn.com/w320/mc.png",
        languages: "French",
    },
    {
        name: "Seychelles",
        capital: "Victoria",
        population: 98462,
        flag: "https://flagcdn.com/w320/sc.png",
        languages: "Seychellois Creole, English, French",
    },
    {
        name: "Armenia",
        capital: "Yerevan",
        population: 2963234,
        flag: "https://flagcdn.com/w320/am.png",
        languages: "Armenian",
    },
    {
        name: "China",
        capital: "Beijing",
        population: 1402112000,
        flag: "https://flagcdn.com/w320/cn.png",
        languages: "Chinese",
    },
    {
        name: "Malaysia",
        capital: "Kuala Lumpur",
        population: 32365998,
        flag: "https://flagcdn.com/w320/my.png",
        languages: "English, Malay",
    },
    {
        name: "Åland Islands",
        capital: "Mariehamn",
        population: 29458,
        flag: "https://flagcdn.com/w320/ax.png",
        languages: "Swedish",
    },
    {
        name: "Andorra",
        capital: "Andorra la Vella",
        population: 77265,
        flag: "https://flagcdn.com/w320/ad.png",
        languages: "Catalan",
    },
    {
        name: "Turkey",
        capital: "Ankara",
        population: 84339067,
        flag: "https://flagcdn.com/w320/tr.png",
        languages: "Turkish",
    },
    {
        name: "Wallis and Futuna",
        capital: "Mata-Utu",
        population: 11750,
        flag: "https://flagcdn.com/w320/wf.png",
        languages: "French",
    },
    {
        name: "Ethiopia",
        capital: "Addis Ababa",
        population: 114963583,
        flag: "https://flagcdn.com/w320/et.png",
        languages: "Amharic",
    },
    {
        name: "Paraguay",
        capital: "Asunción",
        population: 7132530,
        flag: "https://flagcdn.com/w320/py.png",
        languages: "Guaraní, Spanish",
    },
    {
        name: "Czechia",
        capital: "Prague",
        population: 10698896,
        flag: "https://flagcdn.com/w320/cz.png",
        languages: "Czech, Slovak",
    },
    {
        name: "Iran",
        capital: "Tehran",
        population: 83992953,
        flag: "https://flagcdn.com/w320/ir.png",
        languages: "Persian (Farsi)",
    },
    {
        name: "Guinea-Bissau",
        capital: "Bissau",
        population: 1967998,
        flag: "https://flagcdn.com/w320/gw.png",
        languages: "Portuguese, Upper Guinea Creole",
    },
    {
        name: "Ghana",
        capital: "Accra",
        population: 31072945,
        flag: "https://flagcdn.com/w320/gh.png",
        languages: "English",
    },
    {
        name: "Netherlands",
        capital: "Amsterdam",
        population: 16655799,
        flag: "https://flagcdn.com/w320/nl.png",
        languages: "Dutch",
    },
    {
        name: "Sweden",
        capital: "Stockholm",
        population: 10353442,
        flag: "https://flagcdn.com/w320/se.png",
        languages: "Swedish",
    },
    {
        name: "Guyana",
        capital: "Georgetown",
        population: 786559,
        flag: "https://flagcdn.com/w320/gy.png",
        languages: "English",
    },
    {
        name: "Brunei",
        capital: "Bandar Seri Begawan",
        population: 437483,
        flag: "https://flagcdn.com/w320/bn.png",
        languages: "Malay",
    },
    {
        name: "Sudan",
        capital: "Khartoum",
        population: 43849269,
        flag: "https://flagcdn.com/w320/sd.png",
        languages: "Arabic, English",
    },
    {
        name: "Austria",
        capital: "Vienna",
        population: 8917205,
        flag: "https://flagcdn.com/w320/at.png",
        languages: "Austro-Bavarian German",
    },
    {
        name: "Venezuela",
        capital: "Caracas",
        population: 28435943,
        flag: "https://flagcdn.com/w320/ve.png",
        languages: "Spanish",
    },
    {
        name: "Eswatini",
        capital: "Mbabane",
        population: 1160164,
        flag: "https://flagcdn.com/w320/sz.png",
        languages: "English, Swazi",
    },
    {
        name: "Palestine",
        capital: "Ramallah",
        population: 4803269,
        flag: "https://flagcdn.com/w320/ps.png",
        languages: "Arabic",
    },
    {
        name: "São Tomé and Príncipe",
        capital: "São Tomé",
        population: 219161,
        flag: "https://flagcdn.com/w320/st.png",
        languages: "Portuguese",
    },
    {
        name: "Northern Mariana Islands",
        capital: "Saipan",
        population: 57557,
        flag: "https://flagcdn.com/w320/mp.png",
        languages: "Carolinian, Chamorro, English",
    },
    {
        name: "Kenya",
        capital: "Nairobi",
        population: 53771300,
        flag: "https://flagcdn.com/w320/ke.png",
        languages: "English, Swahili",
    },
    {
        name: "Papua New Guinea",
        capital: "Port Moresby",
        population: 8947027,
        flag: "https://flagcdn.com/w320/pg.png",
        languages: "English, Hiri Motu, Tok Pisin",
    },
    {
        name: "Chad",
        capital: "N'Djamena",
        population: 16425859,
        flag: "https://flagcdn.com/w320/td.png",
        languages: "Arabic, French",
    },
    {
        name: "Taiwan",
        capital: "Taipei",
        population: 23503349,
        flag: "https://flagcdn.com/w320/tw.png",
        languages: "Chinese",
    },
    {
        name: "Cape Verde",
        capital: "Praia",
        population: 555988,
        flag: "https://flagcdn.com/w320/cv.png",
        languages: "Portuguese",
    },
    {
        name: "Saint Vincent and the Grenadines",
        capital: "Kingstown",
        population: 110947,
        flag: "https://flagcdn.com/w320/vc.png",
        languages: "English",
    },
    {
        name: "Turkmenistan",
        capital: "Ashgabat",
        population: 6031187,
        flag: "https://flagcdn.com/w320/tm.png",
        languages: "Russian, Turkmen",
    },
    {
        name: "Moldova",
        capital: "Chișinău",
        population: 2617820,
        flag: "https://flagcdn.com/w320/md.png",
        languages: "Romanian",
    },
    {
        name: "Romania",
        capital: "Bucharest",
        population: 19286123,
        flag: "https://flagcdn.com/w320/ro.png",
        languages: "Romanian",
    },
    {
        name: "Marshall Islands",
        capital: "Majuro",
        population: 59194,
        flag: "https://flagcdn.com/w320/mh.png",
        languages: "English, Marshallese",
    },
    {
        name: "Isle of Man",
        capital: "Douglas",
        population: 85032,
        flag: "https://flagcdn.com/w320/im.png",
        languages: "English, Manx",
    },
    {
        name: "Antarctica",
        capital: "None capital",
        population: 1000,
        flag: "https://flagcdn.com/w320/aq.png",
        languages: "",
    },
    {
        name: "Laos",
        capital: "Vientiane",
        population: 7275556,
        flag: "https://flagcdn.com/w320/la.png",
        languages: "Lao",
    },
    {
        name: "Namibia",
        capital: "Windhoek",
        population: 2540916,
        flag: "https://flagcdn.com/w320/na.png",
        languages:
            "Afrikaans, German, English, Herero, Khoekhoe, Kwangali, Lozi, Ndonga, Tswana",
    },
    {
        name: "Kuwait",
        capital: "Kuwait City",
        population: 4270563,
        flag: "https://flagcdn.com/w320/kw.png",
        languages: "Arabic",
    },
    {
        name: "Togo",
        capital: "Lomé",
        population: 8278737,
        flag: "https://flagcdn.com/w320/tg.png",
        languages: "French",
    },
    {
        name: "Mexico",
        capital: "Mexico City",
        population: 128932753,
        flag: "https://flagcdn.com/w320/mx.png",
        languages: "Spanish",
    },
    {
        name: "United States",
        capital: "Washington, D.C.",
        population: 329484123,
        flag: "https://flagcdn.com/w320/us.png",
        languages: "English",
    },
    {
        name: "Samoa",
        capital: "Apia",
        population: 198410,
        flag: "https://flagcdn.com/w320/ws.png",
        languages: "English, Samoan",
    },
    {
        name: "Sierra Leone",
        capital: "Freetown",
        population: 7976985,
        flag: "https://flagcdn.com/w320/sl.png",
        languages: "English",
    },
    {
        name: "South Africa",
        capital: "Pretoria",
        population: 59308690,
        flag: "https://flagcdn.com/w320/za.png",
        languages:
            "Afrikaans, English, Southern Ndebele, Northern Sotho, Southern Sotho, Swazi, Tswana, Tsonga, Venda, Xhosa, Zulu",
    },
    {
        name: "Kyrgyzstan",
        capital: "Bishkek",
        population: 6591600,
        flag: "https://flagcdn.com/w320/kg.png",
        languages: "Kyrgyz, Russian",
    },
    {
        name: "Ecuador",
        capital: "Quito",
        population: 17643060,
        flag: "https://flagcdn.com/w320/ec.png",
        languages: "Spanish",
    },
    {
        name: "Slovakia",
        capital: "Bratislava",
        population: 5458827,
        flag: "https://flagcdn.com/w320/sk.png",
        languages: "Slovak",
    },
    {
        name: "Saint Helena, Ascension and Tristan da Cunha",
        capital: "Jamestown",
        population: 53192,
        flag: "https://flagcdn.com/w320/sh.png",
        languages: "English",
    },
    {
        name: "Bouvet Island",
        capital: "None capital",
        population: 0,
        flag: "https://flagcdn.com/w320/bv.png",
        languages: "Norwegian",
    },
    {
        name: "British Indian Ocean Territory",
        capital: "Diego Garcia",
        population: 3000,
        flag: "https://flagcdn.com/w320/io.png",
        languages: "English",
    },
    {
        name: "Qatar",
        capital: "Doha",
        population: 2881060,
        flag: "https://flagcdn.com/w320/qa.png",
        languages: "Arabic",
    },
    {
        name: "Tonga",
        capital: "Nuku'alofa",
        population: 105697,
        flag: "https://flagcdn.com/w320/to.png",
        languages: "English, Tongan",
    },
    {
        name: "Colombia",
        capital: "Bogotá",
        population: 50882884,
        flag: "https://flagcdn.com/w320/co.png",
        languages: "Spanish",
    },
    {
        name: "Malawi",
        capital: "Lilongwe",
        population: 19129955,
        flag: "https://flagcdn.com/w320/mw.png",
        languages: "English, Chewa",
    },
    {
        name: "Cayman Islands",
        capital: "George Town",
        population: 65720,
        flag: "https://flagcdn.com/w320/ky.png",
        languages: "English",
    },
    {
        name: "United Kingdom",
        capital: "London",
        population: 67215293,
        flag: "https://flagcdn.com/w320/gb.png",
        languages: "English",
    },
    {
        name: "Cambodia",
        capital: "Phnom Penh",
        population: 16718971,
        flag: "https://flagcdn.com/w320/kh.png",
        languages: "Khmer",
    },
    {
        name: "Kosovo",
        capital: "Pristina",
        population: 1775378,
        flag: "https://flagcdn.com/w320/xk.png",
        languages: "Albanian, Serbian",
    },
    {
        name: "Serbia",
        capital: "Belgrade",
        population: 6908224,
        flag: "https://flagcdn.com/w320/rs.png",
        languages: "Serbian",
    },
    {
        name: "Italy",
        capital: "Rome",
        population: 59554023,
        flag: "https://flagcdn.com/w320/it.png",
        languages: "Italian",
    },
    {
        name: "Sri Lanka",
        capital: "Sri Jayawardenepura Kotte",
        population: 21919000,
        flag: "https://flagcdn.com/w320/lk.png",
        languages: "Sinhala, Tamil",
    },
    {
        name: "United States Virgin Islands",
        capital: "Charlotte Amalie",
        population: 106290,
        flag: "https://flagcdn.com/w320/vi.png",
        languages: "English",
    },
    {
        name: "Latvia",
        capital: "Riga",
        population: 1901548,
        flag: "https://flagcdn.com/w320/lv.png",
        languages: "Latvian",
    },
    {
        name: "Jamaica",
        capital: "Kingston",
        population: 2961161,
        flag: "https://flagcdn.com/w320/jm.png",
        languages: "English, Jamaican Patois",
    },
    {
        name: "Norfolk Island",
        capital: "Kingston",
        population: 2302,
        flag: "https://flagcdn.com/w320/nf.png",
        languages: "English, Norfuk",
    },
    {
        name: "Anguilla",
        capital: "The Valley",
        population: 13452,
        flag: "https://flagcdn.com/w320/ai.png",
        languages: "English",
    },
    {
        name: "Switzerland",
        capital: "Bern",
        population: 8654622,
        flag: "https://flagcdn.com/w320/ch.png",
        languages: "French, Swiss German, Italian, Romansh",
    },
    {
        name: "Guinea",
        capital: "Conakry",
        population: 13132792,
        flag: "https://flagcdn.com/w320/gn.png",
        languages: "French",
    },
    {
        name: "Croatia",
        capital: "Zagreb",
        population: 4047200,
        flag: "https://flagcdn.com/w320/hr.png",
        languages: "Croatian",
    },
    {
        name: "French Southern and Antarctic Lands",
        capital: "Port-aux-Français",
        population: 400,
        flag: "https://flagcdn.com/w320/tf.png",
        languages: "French",
    },
    {
        name: "Tuvalu",
        capital: "Funafuti",
        population: 11792,
        flag: "https://flagcdn.com/w320/tv.png",
        languages: "English, Tuvaluan",
    },
    {
        name: "Cyprus",
        capital: "Nicosia",
        population: 1207361,
        flag: "https://flagcdn.com/w320/cy.png",
        languages: "Greek, Turkish",
    },
    {
        name: "Indonesia",
        capital: "Jakarta",
        population: 273523621,
        flag: "https://flagcdn.com/w320/id.png",
        languages: "Indonesian",
    },
    {
        name: "Bosnia and Herzegovina",
        capital: "Sarajevo",
        population: 3280815,
        flag: "https://flagcdn.com/w320/ba.png",
        languages: "Bosnian, Croatian, Serbian",
    },
    {
        name: "Djibouti",
        capital: "Djibouti",
        population: 988002,
        flag: "https://flagcdn.com/w320/dj.png",
        languages: "Arabic, French",
    },
    {
        name: "Christmas Island",
        capital: "Flying Fish Cove",
        population: 2072,
        flag: "https://flagcdn.com/w320/cx.png",
        languages: "English",
    },
    {
        name: "Mauritius",
        capital: "Port Louis",
        population: 1265740,
        flag: "https://flagcdn.com/w320/mu.png",
        languages: "English, French, Mauritian Creole",
    },
    {
        name: "Botswana",
        capital: "Gaborone",
        population: 2351625,
        flag: "https://flagcdn.com/w320/bw.png",
        languages: "English, Tswana",
    },
    {
        name: "Burkina Faso",
        capital: "Ouagadougou",
        population: 20903278,
        flag: "https://flagcdn.com/w320/bf.png",
        languages: "French",
    },
    {
        name: "Finland",
        capital: "Helsinki",
        population: 5530719,
        flag: "https://flagcdn.com/w320/fi.png",
        languages: "Finnish, Swedish",
    },
    {
        name: "South Georgia",
        capital: "King Edward Point",
        population: 30,
        flag: "https://flagcdn.com/w320/gs.png",
        languages: "English",
    },
    {
        name: "Gabon",
        capital: "Libreville",
        population: 2225728,
        flag: "https://flagcdn.com/w320/ga.png",
        languages: "French",
    },
    {
        name: "Iraq",
        capital: "Baghdad",
        population: 40222503,
        flag: "https://flagcdn.com/w320/iq.png",
        languages: "Arabic, Aramaic, Sorani",
    },
    {
        name: "Egypt",
        capital: "Cairo",
        population: 102334403,
        flag: "https://flagcdn.com/w320/eg.png",
        languages: "Arabic",
    },
    {
        name: "Vietnam",
        capital: "Hanoi",
        population: 97338583,
        flag: "https://flagcdn.com/w320/vn.png",
        languages: "Vietnamese",
    },
    {
        name: "DR Congo",
        capital: "Kinshasa",
        population: 108407721,
        flag: "https://flagcdn.com/w320/cd.png",
        languages: "French, Kikongo, Lingala, Tshiluba, Swahili",
    },
    {
        name: "Australia",
        capital: "Canberra",
        population: 25687041,
        flag: "https://flagcdn.com/w320/au.png",
        languages: "English",
    },
    {
        name: "Nigeria",
        capital: "Abuja",
        population: 206139587,
        flag: "https://flagcdn.com/w320/ng.png",
        languages: "English",
    },
    {
        name: "Zimbabwe",
        capital: "Harare",
        population: 14862927,
        flag: "https://flagcdn.com/w320/zw.png",
        languages:
            "Chibarwe, English, Kalanga, Khoisan, Ndau, Northern Ndebele, Chewa, Shona, Sotho, Tonga, Tswana, Tsonga, Venda, Xhosa, Zimbabwean Sign Language",
    },
    {
        name: "North Macedonia",
        capital: "Skopje",
        population: 2077132,
        flag: "https://flagcdn.com/w320/mk.png",
        languages: "Macedonian",
    },
    {
        name: "Micronesia",
        capital: "Palikir",
        population: 115021,
        flag: "https://flagcdn.com/w320/fm.png",
        languages: "English",
    },
    {
        name: "Republic of the Congo",
        capital: "Brazzaville",
        population: 5657000,
        flag: "https://flagcdn.com/w320/cg.png",
        languages: "French, Kikongo, Lingala",
    },
    {
        name: "Liberia",
        capital: "Monrovia",
        population: 5057677,
        flag: "https://flagcdn.com/w320/lr.png",
        languages: "English",
    },
    {
        name: "Cook Islands",
        capital: "Avarua",
        population: 18100,
        flag: "https://flagcdn.com/w320/ck.png",
        languages: "English, Cook Islands Māori",
    },
    {
        name: "Puerto Rico",
        capital: "San Juan",
        population: 3194034,
        flag: "https://flagcdn.com/w320/pr.png",
        languages: "English, Spanish",
    },
    {
        name: "Argentina",
        capital: "Buenos Aires",
        population: 45376763,
        flag: "https://flagcdn.com/w320/ar.png",
        languages: "Guaraní, Spanish",
    },
    {
        name: "Saint Barthélemy",
        capital: "Gustavia",
        population: 4255,
        flag: "https://flagcdn.com/w320/bl.png",
        languages: "French",
    },
    {
        name: "Barbados",
        capital: "Bridgetown",
        population: 287371,
        flag: "https://flagcdn.com/w320/bb.png",
        languages: "English",
    },
    {
        name: "Guadeloupe",
        capital: "Basse-Terre",
        population: 400132,
        flag: "https://flagcdn.com/w320/gp.png",
        languages: "French",
    },
    {
        name: "Eritrea",
        capital: "Asmara",
        population: 5352000,
        flag: "https://flagcdn.com/w320/er.png",
        languages: "Arabic, English, Tigrinya",
    },
    {
        name: "Myanmar",
        capital: "Naypyidaw",
        population: 54409794,
        flag: "https://flagcdn.com/w320/mm.png",
        languages: "Burmese",
    },
    {
        name: "Ivory Coast",
        capital: "Yamoussoukro",
        population: 26378275,
        flag: "https://flagcdn.com/w320/ci.png",
        languages: "French",
    },
    {
        name: "Yemen",
        capital: "Sana'a",
        population: 29825968,
        flag: "https://flagcdn.com/w320/ye.png",
        languages: "Arabic",
    },
    {
        name: "Aruba",
        capital: "Oranjestad",
        population: 106766,
        flag: "https://flagcdn.com/w320/aw.png",
        languages: "Dutch, Papiamento",
    },
    {
        name: "Bangladesh",
        capital: "Dhaka",
        population: 164689383,
        flag: "https://flagcdn.com/w320/bd.png",
        languages: "Bengali",
    },
    {
        name: "Suriname",
        capital: "Paramaribo",
        population: 586634,
        flag: "https://flagcdn.com/w320/sr.png",
        languages: "Dutch",
    },
    {
        name: "Brazil",
        capital: "Brasília",
        population: 212559409,
        flag: "https://flagcdn.com/w320/br.png",
        languages: "Portuguese",
    },
    {
        name: "Ireland",
        capital: "Dublin",
        population: 4994724,
        flag: "https://flagcdn.com/w320/ie.png",
        languages: "English, Irish",
    },
    {
        name: "Luxembourg",
        capital: "Luxembourg",
        population: 632275,
        flag: "https://flagcdn.com/w320/lu.png",
        languages: "German, French, Luxembourgish",
    },
    {
        name: "Tunisia",
        capital: "Tunis",
        population: 11818618,
        flag: "https://flagcdn.com/w320/tn.png",
        languages: "Arabic",
    },
    {
        name: "Belgium",
        capital: "Brussels",
        population: 11555997,
        flag: "https://flagcdn.com/w320/be.png",
        languages: "German, French, Dutch",
    },
    {
        name: "Mayotte",
        capital: "Mamoudzou",
        population: 226915,
        flag: "https://flagcdn.com/w320/yt.png",
        languages: "French",
    },
    {
        name: "Curaçao",
        capital: "Willemstad",
        population: 155014,
        flag: "https://flagcdn.com/w320/cw.png",
        languages: "English, Dutch, Papiamento",
    },
    {
        name: "Réunion",
        capital: "Saint-Denis",
        population: 840974,
        flag: "https://flagcdn.com/w320/re.png",
        languages: "French",
    },
    {
        name: "Vanuatu",
        capital: "Port Vila",
        population: 307150,
        flag: "https://flagcdn.com/w320/vu.png",
        languages: "Bislama, English, French",
    },
    {
        name: "Heard Island and McDonald Islands",
        capital: "None capital",
        population: 0,
        flag: "https://flagcdn.com/w320/hm.png",
        languages: "English",
    },
    {
        name: "Antigua and Barbuda",
        capital: "Saint John's",
        population: 97928,
        flag: "https://flagcdn.com/w320/ag.png",
        languages: "English",
    },
    {
        name: "Cuba",
        capital: "Havana",
        population: 11326616,
        flag: "https://flagcdn.com/w320/cu.png",
        languages: "Spanish",
    },
    {
        name: "Burundi",
        capital: "Gitega",
        population: 11890781,
        flag: "https://flagcdn.com/w320/bi.png",
        languages: "French, Kirundi",
    },
    {
        name: "Bolivia",
        capital: "Sucre",
        population: 11673029,
        flag: "https://flagcdn.com/w320/bo.png",
        languages: "Aymara, Guaraní, Quechua, Spanish",
    },
    {
        name: "Faroe Islands",
        capital: "Tórshavn",
        population: 48865,
        flag: "https://flagcdn.com/w320/fo.png",
        languages: "Danish, Faroese",
    },
    {
        name: "American Samoa",
        capital: "Pago Pago",
        population: 55197,
        flag: "https://flagcdn.com/w320/as.png",
        languages: "English, Samoan",
    },
    {
        name: "Saint Pierre and Miquelon",
        capital: "Saint-Pierre",
        population: 6069,
        flag: "https://flagcdn.com/w320/pm.png",
        languages: "French",
    },
    {
        name: "Poland",
        capital: "Warsaw",
        population: 37950802,
        flag: "https://flagcdn.com/w320/pl.png",
        languages: "Polish",
    },
    {
        name: "Canada",
        capital: "Ottawa",
        population: 38005238,
        flag: "https://flagcdn.com/w320/ca.png",
        languages: "English, French",
    },
    {
        name: "Guatemala",
        capital: "Guatemala City",
        population: 16858333,
        flag: "https://flagcdn.com/w320/gt.png",
        languages: "Spanish",
    },
    {
        name: "Greece",
        capital: "Athens",
        population: 10715549,
        flag: "https://flagcdn.com/w320/gr.png",
        languages: "Greek",
    },
    {
        name: "North Korea",
        capital: "Pyongyang",
        population: 25778815,
        flag: "https://flagcdn.com/w320/kp.png",
        languages: "Korean",
    },
    {
        name: "Uganda",
        capital: "Kampala",
        population: 45741000,
        flag: "https://flagcdn.com/w320/ug.png",
        languages: "English, Swahili",
    },
    {
        name: "Afghanistan",
        capital: "Kabul",
        population: 40218234,
        flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
        languages: "Dari, Pashto, Turkmen",
    },
    {
        name: "British Virgin Islands",
        capital: "Road Town",
        population: 30237,
        flag: "https://flagcdn.com/w320/vg.png",
        languages: "English",
    },
    {
        name: "Azerbaijan",
        capital: "Baku",
        population: 10110116,
        flag: "https://flagcdn.com/w320/az.png",
        languages: "Azerbaijani, Russian",
    },
    {
        name: "Mauritania",
        capital: "Nouakchott",
        population: 4649660,
        flag: "https://flagcdn.com/w320/mr.png",
        languages: "Arabic",
    },
    {
        name: "Portugal",
        capital: "Lisbon",
        population: 10305564,
        flag: "https://flagcdn.com/w320/pt.png",
        languages: "Portuguese",
    },
    {
        name: "Sint Maarten",
        capital: "Philipsburg",
        population: 40812,
        flag: "https://flagcdn.com/w320/sx.png",
        languages: "English, French, Dutch",
    },
    {
        name: "Mongolia",
        capital: "Ulan Bator",
        population: 3278292,
        flag: "https://flagcdn.com/w320/mn.png",
        languages: "Mongolian",
    },
    {
        name: "Solomon Islands",
        capital: "Honiara",
        population: 686878,
        flag: "https://flagcdn.com/w320/sb.png",
        languages: "English",
    },
    {
        name: "Uzbekistan",
        capital: "Tashkent",
        population: 34232050,
        flag: "https://flagcdn.com/w320/uz.png",
        languages: "Russian, Uzbek",
    },
    {
        name: "Philippines",
        capital: "Manila",
        population: 109581085,
        flag: "https://flagcdn.com/w320/ph.png",
        languages: "English, Filipino",
    },
    {
        name: "El Salvador",
        capital: "San Salvador",
        population: 6486201,
        flag: "https://flagcdn.com/w320/sv.png",
        languages: "Spanish",
    },
    {
        name: "Bahrain",
        capital: "Manama",
        population: 1701583,
        flag: "https://flagcdn.com/w320/bh.png",
        languages: "Arabic",
    },
    {
        name: "Albania",
        capital: "Tirana",
        population: 2837743,
        flag: "https://flagcdn.com/w320/al.png",
        languages: "Albanian",
    },
    {
        name: "Georgia",
        capital: "Tbilisi",
        population: 3714000,
        flag: "https://flagcdn.com/w320/ge.png",
        languages: "Georgian",
    },
    {
        name: "Bhutan",
        capital: "Thimphu",
        population: 771612,
        flag: "https://flagcdn.com/w320/bt.png",
        languages: "Dzongkha",
    },
    {
        name: "Saudi Arabia",
        capital: "Riyadh",
        population: 34813867,
        flag: "https://flagcdn.com/w320/sa.png",
        languages: "Arabic",
    },
    {
        name: "Bahamas",
        capital: "Nassau",
        population: 393248,
        flag: "https://flagcdn.com/w320/bs.png",
        languages: "English",
    },
    {
        name: "United Arab Emirates",
        capital: "Abu Dhabi",
        population: 9890400,
        flag: "https://flagcdn.com/w320/ae.png",
        languages: "Arabic",
    },
    {
        name: "Haiti",
        capital: "Port-au-Prince",
        population: 11402533,
        flag: "https://flagcdn.com/w320/ht.png",
        languages: "French, Haitian Creole",
    },
    {
        name: "Western Sahara",
        capital: "El Aaiún",
        population: 510713,
        flag: "https://flagcdn.com/w320/eh.png",
        languages: "Berber, Hassaniya, Spanish",
    },
    {
        name: "Libya",
        capital: "Tripoli",
        population: 6871287,
        flag: "https://flagcdn.com/w320/ly.png",
        languages: "Arabic",
    },
    {
        name: "Vatican City",
        capital: "Vatican City",
        population: 451,
        flag: "https://flagcdn.com/w320/va.png",
        languages: "Italian, Latin",
    },
    {
        name: "Central African Republic",
        capital: "Bangui",
        population: 4829764,
        flag: "https://flagcdn.com/w320/cf.png",
        languages: "French, Sango",
    },
    {
        name: "Costa Rica",
        capital: "San José",
        population: 5094114,
        flag: "https://flagcdn.com/w320/cr.png",
        languages: "Spanish",
    },
    {
        name: "Thailand",
        capital: "Bangkok",
        population: 69799978,
        flag: "https://flagcdn.com/w320/th.png",
        languages: "Thai",
    },
    {
        name: "Greenland",
        capital: "Nuuk",
        population: 56367,
        flag: "https://flagcdn.com/w320/gl.png",
        languages: "Greenlandic",
    },
    {
        name: "French Guiana",
        capital: "Cayenne",
        population: 254541,
        flag: "https://flagcdn.com/w320/gf.png",
        languages: "French",
    },
    {
        name: "Morocco",
        capital: "Rabat",
        population: 36910558,
        flag: "https://flagcdn.com/w320/ma.png",
        languages: "Arabic, Berber",
    },
    {
        name: "Tanzania",
        capital: "Dodoma",
        population: 59734213,
        flag: "https://flagcdn.com/w320/tz.png",
        languages: "English, Swahili",
    },
    {
        name: "Saint Kitts and Nevis",
        capital: "Basseterre",
        population: 53192,
        flag: "https://flagcdn.com/w320/kn.png",
        languages: "English",
    },
    {
        name: "Hong Kong",
        capital: "City of Victoria",
        population: 7500700,
        flag: "https://flagcdn.com/w320/hk.png",
        languages: "English, Chinese",
    },
    {
        name: "Bermuda",
        capital: "Hamilton",
        population: 63903,
        flag: "https://flagcdn.com/w320/bm.png",
        languages: "English",
    },
    {
        name: "Guam",
        capital: "Hagåtña",
        population: 168783,
        flag: "https://flagcdn.com/w320/gu.png",
        languages: "Chamorro, English, Spanish",
    },
    {
        name: "Ukraine",
        capital: "Kyiv",
        population: 44134693,
        flag: "https://flagcdn.com/w320/ua.png",
        languages: "Ukrainian",
    },
    {
        name: "Macau",
        capital: "None capital",
        population: 649342,
        flag: "https://flagcdn.com/w320/mo.png",
        languages: "Portuguese, Chinese",
    },
    {
        name: "Mozambique",
        capital: "Maputo",
        population: 31255435,
        flag: "https://flagcdn.com/w320/mz.png",
        languages: "Portuguese",
    },
    {
        name: "Dominican Republic",
        capital: "Santo Domingo",
        population: 10847904,
        flag: "https://flagcdn.com/w320/do.png",
        languages: "Spanish",
    },
    {
        name: "Montserrat",
        capital: "Plymouth",
        population: 4922,
        flag: "https://flagcdn.com/w320/ms.png",
        languages: "English",
    },
    {
        name: "Israel",
        capital: "Jerusalem",
        population: 9216900,
        flag: "https://flagcdn.com/w320/il.png",
        languages: "Arabic, Hebrew",
    },
    {
        name: "Panama",
        capital: "Panama City",
        population: 4314768,
        flag: "https://flagcdn.com/w320/pa.png",
        languages: "Spanish",
    },
    {
        name: "Bulgaria",
        capital: "Sofia",
        population: 6927288,
        flag: "https://flagcdn.com/w320/bg.png",
        languages: "Bulgarian",
    },
    {
        name: "Senegal",
        capital: "Dakar",
        population: 16743930,
        flag: "https://flagcdn.com/w320/sn.png",
        languages: "French",
    },
    {
        name: "Denmark",
        capital: "Copenhagen",
        population: 5831404,
        flag: "https://flagcdn.com/w320/dk.png",
        languages: "Danish",
    },
    {
        name: "South Sudan",
        capital: "Juba",
        population: 11193729,
        flag: "https://flagcdn.com/w320/ss.png",
        languages: "English",
    },
    {
        name: "Gambia",
        capital: "Banjul",
        population: 2416664,
        flag: "https://flagcdn.com/w320/gm.png",
        languages: "English",
    },
    {
        name: "Oman",
        capital: "Muscat",
        population: 5106622,
        flag: "https://flagcdn.com/w320/om.png",
        languages: "Arabic",
    },
    {
        name: "Russia",
        capital: "Moscow",
        population: 144104080,
        flag: "https://flagcdn.com/w320/ru.png",
        languages: "Russian",
    },
    {
        name: "Angola",
        capital: "Luanda",
        population: 32866268,
        flag: "https://flagcdn.com/w320/ao.png",
        languages: "Portuguese",
    },
    {
        name: "Equatorial Guinea",
        capital: "Malabo",
        population: 1402985,
        flag: "https://flagcdn.com/w320/gq.png",
        languages: "French, Portuguese, Spanish",
    },
    {
        name: "Nepal",
        capital: "Kathmandu",
        population: 29136808,
        flag: "https://flagcdn.com/w320/np.png",
        languages: "Nepali",
    },
    {
        name: "Germany",
        capital: "Berlin",
        population: 83240525,
        flag: "https://flagcdn.com/w320/de.png",
        languages: "German",
    },
    {
        name: "Jersey",
        capital: "Saint Helier",
        population: 100800,
        flag: "https://flagcdn.com/w320/je.png",
        languages: "English, French, Jèrriais",
    },
    {
        name: "Comoros",
        capital: "Moroni",
        population: 869595,
        flag: "https://flagcdn.com/w320/km.png",
        languages: "Arabic, French, Comorian",
    },
    {
        name: "India",
        capital: "New Delhi",
        population: 1380004385,
        flag: "https://flagcdn.com/w320/in.png",
        languages: "English, Hindi, Tamil",
    },
    {
        name: "Hungary",
        capital: "Budapest",
        population: 9749763,
        flag: "https://flagcdn.com/w320/hu.png",
        languages: "Hungarian",
    },
    {
        name: "Timor-Leste",
        capital: "Dili",
        population: 1318442,
        flag: "https://flagcdn.com/w320/tl.png",
        languages: "Portuguese, Tetum",
    },
    {
        name: "French Polynesia",
        capital: "Papeetē",
        population: 280904,
        flag: "https://flagcdn.com/w320/pf.png",
        languages: "French",
    },
    {
        name: "Falkland Islands",
        capital: "Stanley",
        population: 2563,
        flag: "https://flagcdn.com/w320/fk.png",
        languages: "English",
    },
    {
        name: "Dominica",
        capital: "Roseau",
        population: 71991,
        flag: "https://flagcdn.com/w320/dm.png",
        languages: "English",
    },
    {
        name: "Malta",
        capital: "Valletta",
        population: 525285,
        flag: "https://flagcdn.com/w320/mt.png",
        languages: "English, Maltese",
    },
    {
        name: "Pitcairn Islands",
        capital: "Adamstown",
        population: 56,
        flag: "https://flagcdn.com/w320/pn.png",
        languages: "English",
    },
    {
        name: "Trinidad and Tobago",
        capital: "Port of Spain",
        population: 1399491,
        flag: "https://flagcdn.com/w320/tt.png",
        languages: "English",
    },
    {
        name: "Guernsey",
        capital: "St. Peter Port",
        population: 62999,
        flag: "https://flagcdn.com/w320/gg.png",
        languages: "English, French, Guernésiais",
    },
    {
        name: "Niger",
        capital: "Niamey",
        population: 24206636,
        flag: "https://flagcdn.com/w320/ne.png",
        languages: "French",
    },
    {
        name: "Gibraltar",
        capital: "Gibraltar",
        population: 33691,
        flag: "https://flagcdn.com/w320/gi.png",
        languages: "English",
    },
    {
        name: "Saint Lucia",
        capital: "Castries",
        population: 183629,
        flag: "https://flagcdn.com/w320/lc.png",
        languages: "English",
    },
    {
        name: "Belize",
        capital: "Belmopan",
        population: 397621,
        flag: "https://flagcdn.com/w320/bz.png",
        languages: "Belizean Creole, English, Spanish",
    },
    {
        name: "Kiribati",
        capital: "South Tarawa",
        population: 119446,
        flag: "https://flagcdn.com/w320/ki.png",
        languages: "English, Gilbertese",
    },
    {
        name: "Madagascar",
        capital: "Antananarivo",
        population: 27691019,
        flag: "https://flagcdn.com/w320/mg.png",
        languages: "French, Malagasy",
    },
    {
        name: "South Korea",
        capital: "Seoul",
        population: 51780579,
        flag: "https://flagcdn.com/w320/kr.png",
        languages: "Korean",
    },
    {
        name: "United States Minor Outlying Islands",
        capital: "Washington DC",
        population: 300,
        flag: "https://flagcdn.com/w320/um.png",
        languages: "English",
    },
    {
        name: "Slovenia",
        capital: "Ljubljana",
        population: 2100126,
        flag: "https://flagcdn.com/w320/si.png",
        languages: "Slovene",
    },
    {
        name: "Martinique",
        capital: "Fort-de-France",
        population: 378243,
        flag: "https://flagcdn.com/w320/mq.png",
        languages: "French",
    },
    {
        name: "Niue",
        capital: "Alofi",
        population: 1470,
        flag: "https://flagcdn.com/w320/nu.png",
        languages: "English, Niuean",
    },
    {
        name: "Uruguay",
        capital: "Montevideo",
        population: 3473727,
        flag: "https://flagcdn.com/w320/uy.png",
        languages: "Spanish",
    },
    {
        name: "San Marino",
        capital: "City of San Marino",
        population: 33938,
        flag: "https://flagcdn.com/w320/sm.png",
        languages: "Italian",
    },
    {
        name: "Nicaragua",
        capital: "Managua",
        population: 6624554,
        flag: "https://flagcdn.com/w320/ni.png",
        languages: "Spanish",
    },
    {
        name: "Zambia",
        capital: "Lusaka",
        population: 18383956,
        flag: "https://flagcdn.com/w320/zm.png",
        languages: "English",
    },
    {
        name: "Pakistan",
        capital: "Islamabad",
        population: 220892331,
        flag: "https://flagcdn.com/w320/pk.png",
        languages: "English, Urdu",
    },
    {
        name: "Tokelau",
        capital: "Fakaofo",
        population: 1411,
        flag: "https://flagcdn.com/w320/tk.png",
        languages: "English, Samoan, Tokelauan",
    },
    {
        name: "Cameroon",
        capital: "Yaoundé",
        population: 26545864,
        flag: "https://flagcdn.com/w320/cm.png",
        languages: "English, French",
    },
    {
        name: "Liechtenstein",
        capital: "Vaduz",
        population: 38137,
        flag: "https://flagcdn.com/w320/li.png",
        languages: "German",
    },
    {
        name: "Rwanda",
        capital: "Kigali",
        population: 12952209,
        flag: "https://flagcdn.com/w320/rw.png",
        languages: "English, French, Kinyarwanda",
    },
    {
        name: "Belarus",
        capital: "Minsk",
        population: 9398861,
        flag: "https://flagcdn.com/w320/by.png",
        languages: "Belarusian, Russian",
    },
    {
        name: "Maldives",
        capital: "Malé",
        population: 540542,
        flag: "https://flagcdn.com/w320/mv.png",
        languages: "Maldivian",
    },
    {
        name: "Lithuania",
        capital: "Vilnius",
        population: 2794700,
        flag: "https://flagcdn.com/w320/lt.png",
        languages: "Lithuanian",
    },
    {
        name: "Tajikistan",
        capital: "Dushanbe",
        population: 9537642,
        flag: "https://flagcdn.com/w320/tj.png",
        languages: "Russian, Tajik",
    },
    {
        name: "Cocos (Keeling) Islands",
        capital: "West Island",
        population: 544,
        flag: "https://flagcdn.com/w320/cc.png",
        languages: "English",
    },
];
export default countriesData;
